### ISSUE TITLE
Why do you steal code

### ISSUE THREAD

**Issue by monkxy** [Doomlands/blookethack#23]
your code is identical to https://github.com/rxzyx/Blooket-Hacks learn to code rather than plagiarizing skid.

**Comment by Wilke000** [comment]
Yea Jude's right

**Comment by Jude-Gideon** [comment]
Like you added a license to this too, if you had half a brain and could read the license of the code you copied and pasted. Learn to code lmfao, imagine stealing work that's fr just sad.

**Comment by Jude-Gideon** [comment]
Blooket hacks aren't even super hard either, hell it takes more work to copy a repo of hacks than to actually code your own, learn js react and the api and boom, it's simple and not hard. 💀

**Comment by 3kh0** [comment]
@Doomlands is a goofy ass skid

**Comment by Jude-Gideon** [comment]
fr
