### ISSUE TITLE
Code is made by me

### ISSUE THREAD

**Issue by rxzyx** [Doomlands/blookethack#24]
If action is not made, I may be forced to file a DMCA and cause a deletion on this repository.

**Comment by 3kh0** [comment]
@Doomlands is a fucking copycat 💀

**Comment by Jude-Gideon** [comment]
Imagine stealing code

**Comment by 3kh0** [comment]
SKID

**Comment by Jude-Gideon** [comment]
@rxzyx LOOK AT THIS LMAOO https://github.com/Doomlands/Blookethack-menu

**Comment by 3kh0** [comment]
BROOOOO HE STOLE BLOOKETUI TOO

**Comment by Jude-Gideon** [comment]
He can't code lmfaoooo.

**Comment by Jude-Gideon** [comment]
@rxzyx File a DMCA this kids inactive clearly

**Comment by Doomlands** [comment]
💀

**Comment by Jude-Gideon** [comment]
> 💀

Takedown the code you didn't make this, you're going to get sued

**Comment by 3kh0** [comment]
YOOOOOOOOOOOOOOOOOOOOOOOOO SKID MAN IS HERE

**Comment by Jude-Gideon** [comment]
FR

**Comment by Jude-Gideon** [comment]
Im taking a science test rn LMFAOO

**Comment by Jude-Gideon** [comment]
Take down the code skid

**Comment by Jude-Gideon** [comment]
you cant code

**Comment by Jude-Gideon** [comment]
this has happend to you multiple times

**Comment by rxzyx** [comment]
Clearly Mr. Ignorant doesn’t care, well; you were warned! DMCA will be filed today.

**Comment by 3kh0** [comment]
@rxzyx DMCA this bitch into the ground

**Comment by Jude-Gideon** [comment]
Make sure to also DMCA the other kid.

**Comment by Doomlands** [comment]
What other kid also needs you can't get sued for a hack

**Comment by 3kh0** [comment]
@Doomlands you are gonna get fucked, L bozo

**Comment by Doomlands** [comment]
Calm down also who says l bozo💀anyway I'm deleting it

**Comment by Jude-Gideon** [comment]
> Calm down also who says l bozo💀anyway I'm deleting it

It doesn't take 20 minutes to delete code, quit using the skull emoji you've continuously stole code it's your fault stfu.

**Comment by rxzyx** [comment]
> Calm down also who says l bozo💀anyway I'm deleting it

Waiting. Last chance.

**Comment by Jude-Gideon** [comment]
> > Calm down also who says l bozo💀anyway I'm deleting it
> 
> Waiting. Last chance.

He's not gonna just DMCA.

**Comment by 3kh0** [comment]
@rxzyx dmca him, he is not gonna do anything

**Comment by prndndndndnndnd** [comment]
bro jude  it is not allowed to spam
What is not allowed on GitHub?
Spam and Inauthentic Activity on GitHub

**Comment by prndndndndnndnd** [comment]
attualy i was going to github for this vialotin of terms

**Comment by prndndndndnndnd** [comment]
image beause jude-gideion

**Comment by Jude-Gideon** [comment]
> attualy i was going to github for this vialotin of terms

being under 13 is against tos

**Comment by Doomlands** [comment]
I'm not under 13 tho

**Comment by Jude-Gideon** [comment]
> I'm not under 13 tho

Not you.

**Comment by 3kh0** [comment]
@rxzyx dmca his ass

**Comment by prndndndndnndnd** [comment]
bro shut your mouth up 3kh0

**Comment by 3kh0** [comment]
@prndndndndnndnd shut your tangerine mr clean can i get a jellybean urine stain rusty drain destiny 2 dlc campaign flint and steel banana peel dream just did a face reveal ass up you are a no body

**Comment by Jude-Gideon** [comment]
> bro shut your mouth up 3kh0

You're gonna get banned on GitHub
