### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by Minesraft2** [Doomlands/blookethack#36]
[ANTI-BAN](https://github.com/Doomlands/blookethack/blob/main/ANTI-BAN) [Correct Answer](https://github.com/Doomlands/blookethack/blob/main/Correct%20Answer) and [SHOW ANSWER](https://github.com/Doomlands/blookethack/blob/main/SHOW%20ANSWER) were all stolen from my repository, please remove them or I will have to submit a DMCA against you.

**Comment by monkxy** [comment]
> [ANTI-BAN](https://github.com/Doomlands/blookethack/blob/main/ANTI-BAN) [Correct Answer](https://github.com/Doomlands/blookethack/blob/main/Correct%20Answer) and [SHOW ANSWER](https://github.com/Doomlands/blookethack/blob/main/SHOW%20ANSWER) were all stolen from my repository, please remove them or I will have to submit a DMCA against you.

Actually all the code is due to the other scripts being stole from RX, see previous issues.

**Comment by Minesraft2** [comment]
The add tokens script is really old and doesn't even work, so idrc about that
